### ISSUE TITLE
Mostrar nome no editar nome do roteiro,users (Frontend-Forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#10]
**ROTEIRO**
![image](https://user-images.githubusercontent.com/47995532/81102097-02a2fb00-8f07-11ea-86c1-d42fcb7d9288.png)
**UTILIZADORES**
![image](https://user-images.githubusercontent.com/47995532/81102222-39791100-8f07-11ea-9a6a-e37ce6647275.png)

**Comment by BernardoAlegria** [comment]
https://github.com/iptomar/PSI-Grupo-B-2019-2020/commit/d799285348b690c1eae9c93f7757dac5e007ce1f  Tratou da parte dos utilizadores. Para as rotas pelo que vi o problema ja foi resolvido entretanto.
