### ISSUE TITLE
Role field em falta no editar utilizador(Frontend-Forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#11]
![image](https://user-images.githubusercontent.com/47995532/81102983-4b0ee880-8f08-11ea-997c-8cfb90bc762c.png)

**Comment by BernardoAlegria** [comment]
Corrigido no commit https://github.com/iptomar/PSI-Grupo-B-2019-2020/commit/d799285348b690c1eae9c93f7757dac5e007ce1f .
