### ISSUE TITLE
Adição do ponto de interesse com a rota não mostra em que rotas está(Frontend-Forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#13]
![image](https://user-images.githubusercontent.com/47995532/81104481-7b578680-8f0a-11ea-85fd-ed947c33840c.png)

**Comment by BernardoAlegria** [comment]
Esta pagina entretanto foi alterada e resolveram o problema. 
![imagem](https://user-images.githubusercontent.com/46168857/81510877-2d2cf380-930d-11ea-9daa-41fe81cafbb7.png)
