### ISSUE TITLE
Lables fora do sitio + botão apagar utilizador não confirma e aparece somente o registo anterior(Frontend-Forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#15]
![image](https://user-images.githubusercontent.com/47995532/81105529-fec5a780-8f0b-11ea-8b1f-9de8d18f05ee.png)

**Comment by BernardoAlegria** [comment]
Corrigido pelo commit https://github.com/iptomar/PSI-Grupo-B-2019-2020/commit/8c0d9af00fe7566732ebe0e0aed9b96ddb92e97e
