### ISSUE TITLE
Registar vai para Login

### ISSUE THREAD

**Issue by ToCBarros** [iptomar/PSI-Grupo-B-2019-2020#17]
![loginbug](https://user-images.githubusercontent.com/48324552/81930506-9304ce00-95e0-11ea-8e72-43814d3b8d88.png)

**Comment by BernardoAlegria** [comment]
Isto é suposto acontecer, pelo menos por agora, porque apenas os admin podem criar utilizadores.

**Comment by LBadalo** [comment]
Fechado, pois apenas o administrador pode fazer o registo por agora
