### ISSUE TITLE
Na criação dos pontos de interesse, é possível criar vértices sem coordenadas

### ISSUE THREAD

**Issue by ToCBarros** [iptomar/PSI-Grupo-B-2019-2020#19]
![image](https://user-images.githubusercontent.com/48324552/82355709-7d394380-99fa-11ea-8034-ab22ee3a20fe.png)

**Comment by tugamars** [comment]
https://github.com/iptomar/PSI-Grupo-B-2019-2020/issues/20#issuecomment-631533545

**Comment by danielascserra** [comment]
ja ta resolvido
