### ISSUE TITLE
Clicar para adicionar imagens em "criar pontos de interesse" vai para uma pagina em branco

### ISSUE THREAD

**Issue by ToCBarros** [iptomar/PSI-Grupo-B-2019-2020#20]
![image](https://user-images.githubusercontent.com/48324552/82356503-91ca0b80-99fb-11ea-97bc-12f80532939b.png)

**Comment by tugamars** [comment]
É preciso adicionar validação de se os campos estão preenchidos ou não antes de os adicionar!
