### ISSUE TITLE
Ao fazer Login vai diretamente para a pagina dos Pontos de Interesse

### ISSUE THREAD

**Issue by ToCBarros** [iptomar/PSI-Grupo-B-2019-2020#21]
![image](https://user-images.githubusercontent.com/48324552/82358517-8b895e80-99fe-11ea-954e-da34381c9d55.png)
![image](https://user-images.githubusercontent.com/48324552/82358747-dc00bc00-99fe-11ea-8e1a-27b50c3d839a.png)

**Comment by danielascserra** [comment]
resolvido
