### ISSUE TITLE
Criação de um autor com o mesmo nome (Frontend-Forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#22]
![image](https://user-images.githubusercontent.com/47995532/82362018-972b5400-9a03-11ea-8f07-a97f2885c33c.png)

**Comment by tugamars** [comment]
Os autores podem ter o mesmo nome, não existe nenhum bug. Uma vez que podem existir, por exemplo, dois "Joaquim Almeida", sendo que para já é irrelevante mas de futuro poderão ser adicionadas mais propriedades ao autor.

**Comment by LBadalo** [comment]
Eu não meti como fosse bug, meti para avisar que isto depois tem que ser corrigido mais tarde

**Comment by danielascserra** [comment]
Badalo isso nao precisa de ser corrigido.. assim como tens tambem nos pontos de interesse e nos roteiros nomes iguais ..aí é igual.
