### ISSUE TITLE
Role field em falta no registo (Frontend-forms)

### ISSUE THREAD

**Issue by LBadalo** [iptomar/PSI-Grupo-B-2019-2020#8]
![image](https://user-images.githubusercontent.com/47995532/81100907-35e48a80-8f05-11ea-9850-1098cfc4a376.png)

**Comment by BernardoAlegria** [comment]
Com o commit https://github.com/iptomar/PSI-Grupo-B-2019-2020/commit/0e2cdd393c29f68168b2ff0b7f82eacf968fb7c1 penso que essa situação se encontra corrigida
